# # docker-compose.yml

version: '3'
services:
  minio:
    image: minio/minio
    container_name: mlflow_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    restart: always
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc
    depends_on:
      - minio
    container_name: mc
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set minio http://minio:9000 minio_user minio_password && /usr/bin/mc mb minio/mlflow-storage; exit 0; "

volumes:
  minio_data: